# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hw_malfunction',
            name='hsectors',
        ),
        migrations.RemoveField(
            model_name='hw_malfunction',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='hw_malfunction',
            name='user_sector',
        ),
        migrations.DeleteModel(
            name='hw_malfunction',
        ),
    ]
