# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-10 09:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_auto_20180610_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='hw_malfunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fullname', models.CharField(max_length=120, verbose_name='اسم المستخدم')),
                ('pc_type', models.CharField(max_length=120, verbose_name='نوع الكومبيوتر')),
                ('problem_date', models.DateTimeField(verbose_name='تاريخ المشكله')),
                ('problem_desc', models.TextField(verbose_name='وصف المشكله')),
                ('timestamp', models.DateField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ip', models.CharField(max_length=120, null=True)),
                ('closed_by', models.CharField(max_length=120, null=True)),
                ('close_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('hsectors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hsectors', verbose_name='رئاسة القطاعات')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sector', verbose_name='القطاع')),
            ],
        ),
    ]
