# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20180611_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hw_malfunction',
            name='id',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
