# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-12 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20180612_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_blueprint',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_copier',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_device',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_lab',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_pc',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_printer',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_scanner',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='junk_parts',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
    ]
