# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20180612_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_accesspoint',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_rack',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_repeater',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_router',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_server',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_stick',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asset_switch',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=120, primary_key=True, serialize=False),
        ),
    ]
