# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-24 07:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20180613_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset_printer',
            name='printer_type',
            field=models.CharField(choices=[('LaserJet', 'LaserJet'), ('OfficeJet', 'OfficeJet'), ('DeskJet', 'DeskJet'), ('InkJet', 'InkJet'), ('MFP', 'MFP')], max_length=120, verbose_name='نوع الطابعه'),
        ),
        migrations.AlterField(
            model_name='junk_parts',
            name='user_sector',
            field=models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sector', verbose_name=' القطاع'),
        ),
    ]
