# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20180624_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchassets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_bransh', models.CharField(blank=True, choices=[('الفواله', 'الفواله'), ('المهندسيين', 'المهندسيين'), ('جاردن سيتى', 'جاردن سيتى'), ('سيتى بنك', 'سيتى بنك'), ('قصر النيل', 'قصر النيل'), ('التوفيقيه', 'التوفيقيه')], max_length=120, null=True, verbose_name='اسم الفرع')),
                ('select_user', models.CharField(blank=True, max_length=120, null=True, verbose_name='اسم المستخدم')),
                ('select_object', models.CharField(blank=True, choices=[('COMPUTERS', 'COMPUTERS'), ('LABTOPS', 'LABTOPS'), ('PRINTERS', 'PRINTERS'), ('SCANNERS', 'SCANNERS'), ('COPIERS', 'COPIERS')], max_length=120, null=True, verbose_name='Problem Type')),
                ('processor_type', models.CharField(blank=True, choices=[('celeron', 'celeron'), ('Pentium', 'Pentium'), ('PentiumD', 'PentiumD'), ('Pentium4', 'Pentium4'), ('DualCore', 'DualCore'), ('Core2Duo', 'Core2Duo'), ('CoreI3', 'CoreI3'), ('CoreI5', 'CoreI5'), ('CoreI7', 'CoreI7'), ('', '')], max_length=120, null=True, verbose_name='نوع المعالج')),
                ('joined', models.CharField(blank=True, choices=[('JOINED', 'JOINED'), ('UNJOINED', 'UNJOINED')], max_length=120, null=True, verbose_name='الرپط پالدومين')),
                ('harddisk_size', models.CharField(blank=True, max_length=120, null=True, verbose_name='حجم وحدة التخزين')),
                ('pc_model', models.CharField(blank=True, max_length=120, null=True, verbose_name='موديل الجهاز')),
                ('monitor_type', models.CharField(blank=True, choices=[('CRT', 'CRT'), ('LCD', 'LCD'), ('LED', 'LED')], max_length=120, null=True, verbose_name='نوع الشاشه الجهاز')),
                ('os_license', models.CharField(blank=True, choices=[('Licensed', 'Licensed'), ('No License', 'No License')], max_length=120, null=True, verbose_name='ترخيص نظام التشغيل ')),
                ('lab_model', models.CharField(blank=True, max_length=120, null=True, verbose_name='موديل الجهاز')),
                ('lab_vendor', models.CharField(blank=True, max_length=120, null=True, verbose_name='اسم الشركه المصنعه')),
                ('printer_type', models.CharField(blank=True, choices=[('LaserJet', 'LaserJet'), ('OfficeJet', 'OfficeJet'), ('DeskJet', 'DeskJet'), ('InkJet', 'InkJet'), ('MFP', 'MFP')], max_length=120, null=True, verbose_name='نوع الطابعه')),
                ('printer_model', models.CharField(blank=True, max_length=120, null=True, verbose_name='موديل الطابعه')),
                ('scanner_type', models.CharField(choices=[('LowSpeedNormal', 'LowSpeedNormal'), ('HighSpeedMultiScan', 'HighSpeedMultiScan')], default='Null', max_length=120, verbose_name='نوع الماسح الضوئى')),
                ('scanner_model', models.CharField(max_length=120, verbose_name='موديل الماسح الضوئى')),
                ('copier_model', models.CharField(blank=True, max_length=120, null=True, verbose_name='موديل ماكينة التصوير')),
                ('conn_type', models.CharField(blank=True, choices=[('USB', 'USB'), ('ETHERNET', 'ETHERNET'), ('USB+ETHERNET', 'USB+ETHERNET'), ('NO-DATA-CONNECTION', 'NO-DATA-CONNECTION')], default='NO-DATA-CONNECTION', max_length=120, null=True, verbose_name='نوع التوصيل الشبكى')),
                ('select_hsectors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.hsectors', verbose_name='رئاسة القطاعات')),
                ('select_sector', models.ForeignKey(blank=True, max_length=120, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.sector', verbose_name=' القطاع')),
            ],
        ),
        migrations.AddField(
            model_name='asset_server',
            name='monitor_type',
            field=models.CharField(blank=True, choices=[('CRT', 'CRT'), ('LCD', 'LCD'), ('LED', 'LED')], max_length=120, null=True, verbose_name='نوع الشاشه الجهاز'),
        ),
        migrations.AlterField(
            model_name='asset_pc',
            name='os_version',
            field=models.CharField(choices=[('NONE', 'NONE'), ('WINDOWS XP', 'WINDOWS XP'), ('WINDOWS 7', 'WINDOWS 7'), ('WINDOWS 8', 'WINDOWS 8'), ('WINDOWS 10', 'WINDOWS 10'), ('LINUX', 'LINUX'), ('MS-DOS', 'MS-DOS')], max_length=120, null=True, verbose_name='نسخة نظام التشغيل الحاليه'),
        ),
        migrations.AlterField(
            model_name='asset_pc',
            name='os_version_oem',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('WINDOWS XP', 'WINDOWS XP'), ('WINDOWS 7', 'WINDOWS 7'), ('WINDOWS 8', 'WINDOWS 8'), ('WINDOWS 10', 'WINDOWS 10'), ('LINUX', 'LINUX'), ('MS-DOS', 'MS-DOS')], default='None', max_length=120, null=True, verbose_name='OEM OS LABELED VERSION'),
        ),
        migrations.AlterField(
            model_name='asset_pc',
            name='ram_size',
            field=models.CharField(choices=[('128M', '128M'), ('256M', '256M'), ('512M', '512M'), ('756M', '756M'), ('1G', '1G'), ('1.128G', ''), ('1.256G', '1.256G'), ('1.512G', '1.512G'), ('1.768G', '1.768G'), ('2G', '2G'), ('2.128G', '2.128G'), ('2.256G', '2.256G'), ('2.512G', '2.512G'), ('2.768G', '2.768G'), ('3G', '3G'), ('3.128G', '3.128G'), ('3.256G', '3.256G'), ('3.512G', '3.512G'), ('3.768G', '3.768G'), ('4G', '4G'), ('4.128G', '4.128G'), ('4.256G', '4.256G'), ('4.512G', '4.512G'), ('4.768G', '4.768G'), ('5G', '5G'), ('6G', '6G'), ('7G', '7G'), ('8G', '8G')], max_length=120, verbose_name='حجم الذاكره '),
        ),
    ]
