# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-08 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20180627_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset_server',
            name='monitor_size',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='حچم وموديل الشاشه '),
        ),
        migrations.AlterField(
            model_name='searchassets',
            name='scanner_model',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='موديل الماسح الضوئى'),
        ),
        migrations.AlterField(
            model_name='searchassets',
            name='scanner_type',
            field=models.CharField(blank=True, choices=[('LowSpeedNormal', 'LowSpeedNormal'), ('HighSpeedMultiScan', 'HighSpeedMultiScan')], default='Null', max_length=120, null=True, verbose_name='نوع الماسح الضوئى'),
        ),
        migrations.AlterField(
            model_name='searchassets',
            name='select_object',
            field=models.CharField(blank=True, choices=[('COMPUTERS', 'COMPUTERS'), ('LABTOPS', 'LABTOPS'), ('PRINTERS', 'PRINTERS'), ('SCANNERS', 'SCANNERS'), ('COPIERS', 'COPIERS')], max_length=120, null=True, verbose_name='نوع الاصل'),
        ),
    ]
