# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20180711_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='missions',
            name='it_partners',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(' محمد احمد ', 'محمد احمد '), (' عبد المنعم رفعت ', 'عبد المنعم رفعت '), (' أحمد سعيد ', 'أحمد سعيد '), (' وائل علاء الدين ', 'وائل علاء الدين '), (' مصطفى نادى ', 'مصطفى نادى '), (' احمد رفقى ', 'احمد رفقى '), (' وائل الطويل ', 'وائل الطويل '), (' اسلام عبد الوهاب ', 'اسلام عبد الوهاب '), (' أحمد حجازى ', 'أحمد حجازى '), (' أحمد صلاح ', 'أحمد صلاح '), (' رامز سمير ', 'رامز سمير '), (' أحمد عبيد  ', 'أحمد عبيد  '), (' أحمد إبراهيم ', 'أحمد إبراهيم '), (' محمد جاد ', 'محمد جاد '), (' ياسمين الجوهرى ', 'ياسمين الجوهرى '), (' اميرة عبد العال ', 'اميرة عبد العال '), (' مها محمد ', 'مها محمد '), (' أمجد أبو السعود ', 'أمجد أبو السعود '), (' أسامة فتحى ', 'أسامة فتحى '), (' محمد مصطفى ', 'محمد مصطفى '), (' دينا سراج ', 'دينا سراج '), (' محمد شعبان ', 'محمد شعبان '), (' هانى مصطفى ', 'هانى مصطفى '), (' محمد جاد  ', 'محمد جاد  '), (' محمد احمد ', 'محمد احمد '), (' احمد عصام ', 'احمد عصام '), (' إسلام عبد الوهاب ', 'إسلام عبد الوهاب ')], default='داخل الشرگه', max_length=120, verbose_name='المگان '),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission1',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الاولى'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission10',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه العاشره'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission2',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الثانيه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission3',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الثالثه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission4',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الراپعه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission5',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الخامسه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission6',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه السادسه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission7',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الساپعه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission8',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه الثامنه'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='mission9',
            field=models.TextField(blank=True, max_length=120, verbose_name='المهامه التاسعه'),
        ),
    ]
