# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-11 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20180711_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
