# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_auto_20180711_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missions',
            old_name='out_premisis',
            new_name='m1_out_premisis',
        ),
        migrations.RenameField(
            model_name='missions',
            old_name='place',
            new_name='m1_place',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='mission10',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='mission6',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='mission7',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='mission8',
        ),
        migrations.RemoveField(
            model_name='missions',
            name='mission9',
        ),
        migrations.AddField(
            model_name='missions',
            name='m2_out_premisis',
            field=models.CharField(blank=True, max_length=120, verbose_name='چهة خارچ الشرگه'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m2_place',
            field=models.CharField(blank=True, choices=[('داخل الشرگه', 'داخل الشرگه'), ('چهه اخرى', 'چهه اخرى')], default='داخل الشرگه', max_length=120, verbose_name='المگان '),
        ),
        migrations.AddField(
            model_name='missions',
            name='m3_out_premisis',
            field=models.CharField(blank=True, max_length=120, verbose_name='چهة خارچ الشرگه'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m3_place',
            field=models.CharField(blank=True, choices=[('داخل الشرگه', 'داخل الشرگه'), ('چهه اخرى', 'چهه اخرى')], default='داخل الشرگه', max_length=120, verbose_name='المگان '),
        ),
        migrations.AddField(
            model_name='missions',
            name='m4_out_premisis',
            field=models.CharField(blank=True, max_length=120, verbose_name='چهة خارچ الشرگه'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m4_place',
            field=models.CharField(blank=True, choices=[('داخل الشرگه', 'داخل الشرگه'), ('چهه اخرى', 'چهه اخرى')], default='داخل الشرگه', max_length=120, verbose_name='المگان '),
        ),
        migrations.AddField(
            model_name='missions',
            name='m5_out_premisis',
            field=models.CharField(blank=True, max_length=120, verbose_name='چهة خارچ الشرگه'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m5_place',
            field=models.CharField(blank=True, choices=[('داخل الشرگه', 'داخل الشرگه'), ('چهه اخرى', 'چهه اخرى')], default='داخل الشرگه', max_length=120, verbose_name='المگان '),
        ),
        migrations.AlterField(
            model_name='missions',
            name='bransh',
            field=models.CharField(blank=True, choices=[('الفواله', 'الفواله'), ('المهندسيين', 'المهندسيين'), ('جاردن سيتى', 'جاردن سيتى'), ('سيتى بنك', 'سيتى بنك'), ('قصر النيل', 'قصر النيل'), ('التوفيقيه', 'التوفيقيه')], max_length=120, null=True, verbose_name='اسم الفرع'),
        ),
        migrations.AlterField(
            model_name='missions',
            name='it_partners',
            field=models.CharField(blank=True, choices=[(' محمد احمد ', 'محمد احمد '), (' عبد المنعم رفعت ', 'عبد المنعم رفعت '), (' أحمد سعيد ', 'أحمد سعيد '), (' وائل علاء الدين ', 'وائل علاء الدين '), (' مصطفى نادى ', 'مصطفى نادى '), (' احمد رفقى ', 'احمد رفقى '), (' وائل الطويل ', 'وائل الطويل '), (' اسلام عبد الوهاب ', 'اسلام عبد الوهاب '), (' أحمد حجازى ', 'أحمد حجازى '), (' أحمد صلاح ', 'أحمد صلاح '), (' رامز سمير ', 'رامز سمير '), (' أحمد عبيد  ', 'أحمد عبيد  '), (' أحمد إبراهيم ', 'أحمد إبراهيم '), (' محمد جاد ', 'محمد جاد '), (' ياسمين الجوهرى ', 'ياسمين الجوهرى '), (' اميرة عبد العال ', 'اميرة عبد العال '), (' مها محمد ', 'مها محمد '), (' أمجد أبو السعود ', 'أمجد أبو السعود '), (' أسامة فتحى ', 'أسامة فتحى '), (' محمد مصطفى ', 'محمد مصطفى '), (' دينا سراج ', 'دينا سراج '), (' محمد شعبان ', 'محمد شعبان '), (' هانى مصطفى ', 'هانى مصطفى '), (' محمد جاد  ', 'محمد جاد  '), (' محمد احمد ', 'محمد احمد '), (' احمد عصام ', 'احمد عصام '), (' إسلام عبد الوهاب ', 'إسلام عبد الوهاب ')], default='داخل الشرگه', max_length=120, verbose_name='المشترگين ڤى الاعمال '),
        ),
    ]
