# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20180717_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missions',
            old_name='bransh',
            new_name='m1_bransh',
        ),
        migrations.AddField(
            model_name='missions',
            name='m2_bransh',
            field=models.CharField(blank=True, choices=[('الفواله', 'الفواله'), ('المهندسيين', 'المهندسيين'), ('جاردن سيتى', 'جاردن سيتى'), ('سيتى بنك', 'سيتى بنك'), ('قصر النيل', 'قصر النيل'), ('التوفيقيه', 'التوفيقيه')], max_length=120, null=True, verbose_name='اسم الفرع'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m3_bransh',
            field=models.CharField(blank=True, choices=[('الفواله', 'الفواله'), ('المهندسيين', 'المهندسيين'), ('جاردن سيتى', 'جاردن سيتى'), ('سيتى بنك', 'سيتى بنك'), ('قصر النيل', 'قصر النيل'), ('التوفيقيه', 'التوفيقيه')], max_length=120, null=True, verbose_name='اسم الفرع'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m4_bransh',
            field=models.CharField(blank=True, choices=[('الفواله', 'الفواله'), ('المهندسيين', 'المهندسيين'), ('جاردن سيتى', 'جاردن سيتى'), ('سيتى بنك', 'سيتى بنك'), ('قصر النيل', 'قصر النيل'), ('التوفيقيه', 'التوفيقيه')], max_length=120, null=True, verbose_name='اسم الفرع'),
        ),
        migrations.AddField(
            model_name='missions',
            name='m5_bransh',
            field=models.CharField(blank=True, choices=[('الفواله', 'الفواله'), ('المهندسيين', 'المهندسيين'), ('جاردن سيتى', 'جاردن سيتى'), ('سيتى بنك', 'سيتى بنك'), ('قصر النيل', 'قصر النيل'), ('التوفيقيه', 'التوفيقيه')], max_length=120, null=True, verbose_name='اسم الفرع'),
        ),
    ]
