# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-18 12:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0019_auto_20180717_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='LAW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=120, verbose_name='اسم القضيه')),
                ('case_type', models.CharField(blank=True, max_length=120, null=True, verbose_name='نوع القضيه')),
                ('court_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='تاريخ پدا القضيه')),
                ('case_start_date', models.DateTimeField(blank=True, max_length=120, null=True, verbose_name=' تاريخ پدا القضيه ')),
                ('lawyer_name', models.CharField(blank=True, max_length=120, null=True, verbose_name='اسم المحامى متولى القضيه')),
                ('about_case', models.TextField(blank=True, max_length=120, null=True, verbose_name='نپذه عن القضيه')),
                ('last_case_update', models.CharField(max_length=120, verbose_name='اخر تحديث للقضيه')),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('ip', models.CharField(blank=True, max_length=120, null=True)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
