# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-19 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='court_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='المحگمه المتداول پها القضيه'),
        ),
        migrations.AlterField(
            model_name='law',
            name='last_case_update',
            field=models.TextField(max_length=2048, verbose_name='اخر تحديث للقضيه'),
        ),
    ]
