# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-24 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_auto_20180719_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='search_case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=120, verbose_name='الپحث پاسم القضيه')),
                ('lawyer_name', models.CharField(blank=True, max_length=120, verbose_name=' الپحث پاسم المحامى')),
                ('court_name', models.CharField(blank=True, max_length=120, verbose_name='الپحث پاسم المحگمه ')),
            ],
        ),
    ]
